name       : modem-manager
version    : 1.10.0
release    : 12
source     :
    - git|https://github.com/freedesktop/ModemManager.git : 1.10.0
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.base
summary    : GNOME Modem Manager
description: |
    GNOME Modem Manager
builddeps  :
    - pkgconfig(mbim-glib)
    - pkgconfig(qmi-glib)
setup      : |
    %reconfigure --disable-static \
        --with-systemd-suspend-resume=yes \
        --with-udev-base-dir=%libdir%/udev
build      : |
    %make
install    : |
    %make_install

    # Enable modemmanager service by default
    install -dm00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv %libdir%/systemd/system/ModemManager.service $installdir/%libdir%/systemd/system/multi-user.target.wants    # Create the required alias for it to start via dbus activation
