name       : modem-manager
version    : 1.6.12
release    : 8
source     :
    - https://www.freedesktop.org/software/ModemManager/ModemManager-1.6.12.tar.xz : eefb7615c2c7ebc994abfc2782bfa9e798643a633362b40db96f7f61706a6283
license    :
    - GPL-2.0
    - LGPL-2.1
component  : network.base
summary    : GNOME Modem Manager
description: |
    GNOME Modem Manager
builddeps  :
    - pkgconfig(mbim-glib)
    - pkgconfig(qmi-glib)
setup      : |
    %configure --disable-static \
        --with-suspend-resume=systemd \
        --with-udev-base-dir=%libdir%/udev
build      : |
    %make
install    : |
    %make_install
