name       : modem-manager
version    : 1.10.0
release    : 11
source     :
    - git|https://github.com/freedesktop/ModemManager.git : 1.10.0
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.base
summary    : GNOME Modem Manager
description: |
    GNOME Modem Manager
builddeps  :
    - pkgconfig(mbim-glib)
    - pkgconfig(qmi-glib)
setup      : |
    %reconfigure --disable-static \
        --with-dbus-sys-dir=/usr/share/dbus-1/system.d \
        --with-systemd-suspend-resume=yes \
        --with-udev-base-dir=%libdir%/udev
build      : |
    %make
install    : |
    %make_install

    # Create the required alias for it to start via dbus activation
    install -dm00755 $installdir/%libdir%/systemd/system
    ln -sf %libdir%/systemd/system/ModemManager.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.ModemManager1.service
