name       : modem-manager
version    : 1.6.4
release    : 6
source     :
    - http://www.freedesktop.org/software/ModemManager/ModemManager-1.6.4.tar.xz : cdd5b4cb1e4d7643643a28ccbfc4bb354bfa9cb89a77ea160ebdf7926171c668
license    :
    - GPL-2.0
    - LGPL-2.1
component  : network.base
summary    : GNOME Modem Manager
description: |
    GNOME Modem Manager
builddeps  :
    - pkgconfig(mbim-glib)
    - pkgconfig(qmi-glib)
setup      : |
    %configure --disable-static \
               --with-udev-base-dir=%libdir%/udev
build      : |
    %make
install    : |
    %make_install
