name       : modem-manager
version    : 1.16.2
release    : 16
source     :
    - https://www.freedesktop.org/software/ModemManager/ModemManager-1.16.2.tar.xz : efa9a963499e0885f3f163096d433334143c4937545134ecd682e0157fa591e3
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.base
homepage   : https://gitlab.freedesktop.org/mobile-broadband/ModemManager
summary    : GNOME Modem Manager
description: |
    GNOME Modem Manager
builddeps  :
    - pkgconfig(mbim-glib)
    - pkgconfig(qmi-glib)
    - vala
setup      : |
    %configure --disable-static \
        --with-dbus-sys-dir=/usr/share/dbus-1/system.d \
        --with-systemd-suspend-resume=yes \
        --with-udev-base-dir=%libdir%/udev
build      : |
    %make
install    : |
    %make_install

    # Enable modemmanager service by default
    install -dm00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv %libdir%/systemd/system/ModemManager.service $installdir/%libdir%/systemd/system/multi-user.target.wants    # Create the required alias for it to start via dbus activation
