name       : modem-manager
version    : 1.6.8
release    : 7
source     :
    - https://www.freedesktop.org/software/ModemManager/ModemManager-1.6.8.tar.xz : ffc035c4bfeb07780c4580bb4488ade0ab1d197c3cdf89cb8ab36386cfb34376
license    :
    - GPL-2.0
    - LGPL-2.1
component  : network.base
summary    : GNOME Modem Manager
description: |
    GNOME Modem Manager
builddeps  :
    - pkgconfig(mbim-glib)
    - pkgconfig(qmi-glib)
setup      : |
    %configure --disable-static \
               --with-udev-base-dir=%libdir%/udev
build      : |
    %make
install    : |
    %make_install
