name       : modem-manager
version    : 1.6.12
release    : 9
source     :
    - https://www.freedesktop.org/software/ModemManager/ModemManager-1.6.12.tar.xz : eefb7615c2c7ebc994abfc2782bfa9e798643a633362b40db96f7f61706a6283
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : network.base
summary    : GNOME Modem Manager
description: |
    GNOME Modem Manager
builddeps  :
    - pkgconfig(mbim-glib)
    - pkgconfig(qmi-glib)
setup      : |
    %configure --disable-static \
        --with-dbus-sys-dir=/usr/share/dbus-1/system.d \
        --with-suspend-resume=systemd \
        --with-udev-base-dir=%libdir%/udev
build      : |
    %make
install    : |
    %make_install

    # Create the required alias for it to start via dbus activation
    install -dm00755 $installdir/%libdir%/systemd/system
    ln -sf %libdir%/systemd/system/ModemManager.service $installdir/%libdir%/systemd/system/dbus-org.freedesktop.ModemManager1.service
