name        : modem-manager
version     : 1.4.12
release     : 5
source     :
    - http://www.freedesktop.org/software/ModemManager/ModemManager-1.4.12.tar.xz : 7ef5035375a953b285a742591df0a65fd442f4641ce4d8f4392a41d6d6bc70b3
license     :
    - GPLv2+
summary     : GNOME Modem Manager
builddeps   :
    - pkgconfig(qmi-glib)
    - pkgconfig(mbim-glib)
description : |
    GNOME Modem Manager
setup      : |
    %configure --disable-static \
               --with-udev-base-dir=/usr/lib/udev
build      : |
    %make
install    : |
    %make_install
